// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "";
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "";

if (!supabaseUrl) {
  console.error("ALERTA: A URL do Supabase não chegou no código!");
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
